[package]
name = "minicon-lab-hello-window"
version = "0.0.0"
edition = "2024"
publish = false
build = "build.rs"

[workspace]

[features]
default = []
resourced = []

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
