#!/usr/bin/env python3
"""Render plan/round-baseline.md from a round-receipt.json.

D3 (plan/plan-v0.1.24.md): per-stage timings already live in every receipt;
this turns them into a table nobody has to hand-edit. Only PASS rows are a
baseline -- a BLOCKED or FAILed stage measures how long it took to not
answer the question, which is not a number to chase. Called from
scripts/round.sh after every round; safe to run standalone against any
existing receipt.
"""
import json
import sys


def render(receipt_path: str) -> str:
    with open(receipt_path, encoding="utf-8") as handle:
        receipt = json.load(handle)

    rows = [row for row in receipt.get("stages", []) if row.get("verdict") == "PASS"]
    by_cell: dict[str, list[dict]] = {}
    for row in rows:
        by_cell.setdefault(row["cell"], []).append(row)

    lines = [
        "<!-- Generated by scripts/render-round-baseline.py from a round-receipt.json.",
        "     Do not hand-edit; run scripts/round.sh again to refresh it. -->",
        "",
        "# Round baseline (latest green run)",
        "",
        f"- source: `{receipt.get('source_sha', 'unknown')}`"
        f" ({receipt.get('source_fingerprint', 'unknown')})",
        f"- total: {receipt.get('seconds', '?')}s"
        f", tally: {json.dumps(receipt.get('tally', {}), sort_keys=True)}",
        "",
        "| cell | stage | seconds | detail |",
        "| --- | --- | ---: | --- |",
    ]
    for cell in sorted(by_cell):
        for row in by_cell[cell]:
            detail = row.get("detail", "") or ""
            lines.append(f"| {cell} | {row['stage']} | {row['seconds']} | {detail} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: render-round-baseline.py RECEIPT.json OUTPUT.md", file=sys.stderr)
        return 2
    receipt_path, output_path = sys.argv[1], sys.argv[2]
    try:
        text = render(receipt_path)
    except FileNotFoundError:
        print(f"render-round-baseline: no receipt at {receipt_path}, nothing to render", file=sys.stderr)
        return 0
    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"[round] baseline: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
